This script generates the data for the valence database and the cognitive distortion database

In [7]:
import pandas as pd
import numpy as np
import re

In [8]:
#machine annotate data
data = pd.read_csv('allPredLabel.csv')
len(data)

4520

In [9]:
#all data
sam = pd.read_csv('./Data/sample_5000.csv')
len(sam)

4732

In [10]:
#machine annotate data without foreign languages
data = pd.read_csv('merge2.csv')
len(data)

4520

In [11]:
#select no quote data
dataNoL = data[data['result'] == 0]
len(dataNoL)

3940

In [12]:
#dataNoL
database = pd.DataFrame()
database['text'] = dataNoL['text']
database = database.assign (annotation = 0)
database = database.assign (annotation_date = np.nan)
database = database.assign (userid = data['userid'])
database = database.reset_index()
database = database.assign(id = database.index + 1)
len(database)

3940

In [13]:
#generate an array with 3 numbers
pid = np.random.choice([44553, 22334, 33442], size=3940)

In [14]:
database = database.assign(ParticipantID = pid) 
database = database.drop(['index'], axis=1)
database[0:10]

,text,annotation,annotation_date,userid,id,ParticipantID
0,Is tired of life. I'm tired of always being bl...,0,NaN,ff901930a5eaba2dc939d40571f51bb5,1,22334
1,I'm home and happy to be back. already busy wi...,0,NaN,ff901930a5eaba2dc939d40571f51bb5,2,22334
2,I'm fucking done. I don't need this type of sh...,0,NaN,ff901930a5eaba2dc939d40571f51bb5,3,22334
3,"Dad's home for a month, he's going to be there...",0,NaN,ff901930a5eaba2dc939d40571f51bb5,4,22334
4,*sighs* I just want to go home...sorta. There'...,0,NaN,ff901930a5eaba2dc939d40571f51bb5,5,22334
5,"Morning, everyone. Today's going to be blah wi...",0,NaN,ff901930a5eaba2dc939d40571f51bb5,6,22334
6,"I'm attempting to join the Marine Corps, all t...",0,NaN,ff901930a5eaba2dc939d40571f51bb5,7,33442
7,I was just now told I looked like a vampyre by...,0,NaN,ff901930a5eaba2dc939d40571f51bb5,8,33442
8,i get to go to my aunt's house for part of thi...,0,NaN,ff901930a5eaba2dc939d40571f51bb5,9,22334
9,Went to the doctor's today. she told me that I...,0,NaN,ff901930a5eaba2dc939d40571f51bb5,10,22334

In [15]:
print(len(database[database['ParticipantID'] == 22334]))
print(len(database[database['ParticipantID'] == 44553]))
print(len(database[database['ParticipantID'] == 33442]))

1325
1265
1350

In [16]:
database['ParticipantID'] = database['ParticipantID'].astype(str)
#database['ParticipantID'] = '"' + database.ParticipantID + '"'

In [17]:
database = database[['ParticipantID','id', 'userid','text', 'annotation_date', 'annotation']]
database[0:10]

,ParticipantID,id,userid,text,annotation_date,annotation
0,22334,1,ff901930a5eaba2dc939d40571f51bb5,Is tired of life. I'm tired of always being bl...,NaN,0
1,22334,2,ff901930a5eaba2dc939d40571f51bb5,I'm home and happy to be back. already busy wi...,NaN,0
2,22334,3,ff901930a5eaba2dc939d40571f51bb5,I'm fucking done. I don't need this type of sh...,NaN,0
3,22334,4,ff901930a5eaba2dc939d40571f51bb5,"Dad's home for a month, he's going to be there...",NaN,0
4,22334,5,ff901930a5eaba2dc939d40571f51bb5,*sighs* I just want to go home...sorta. There'...,NaN,0
5,22334,6,ff901930a5eaba2dc939d40571f51bb5,"Morning, everyone. Today's going to be blah wi...",NaN,0
6,33442,7,ff901930a5eaba2dc939d40571f51bb5,"I'm attempting to join the Marine Corps, all t...",NaN,0
7,33442,8,ff901930a5eaba2dc939d40571f51bb5,I was just now told I looked like a vampyre by...,NaN,0
8,22334,9,ff901930a5eaba2dc939d40571f51bb5,i get to go to my aunt's house for part of thi...,NaN,0
9,22334,10,ff901930a5eaba2dc939d40571f51bb5,Went to the doctor's today. she told me that I...,NaN,0

In [18]:
database.to_csv('database3.csv')

5% of the data (n = 197) will be labeled by 2 annotators, therefore 
* 44553 label 66 posts from 22334,
* 22334 label 66 posts from 33442,
* 33442 label 65 posts from 44553,
database3 is just an exmple
the database2 is the one we used in the database, non-english text were mannuall removed. 5% of posts were manually added to each user

#Negative Distortion

In [373]:
####select data that is labeled as negative, since we don't have data yet, so we use the valence dataset
#select no quote data
dataNoL = data[data['result'] == 0]
dataNoL['time'] = pd.to_datetime(dataNoL['time'])

/Users/lucia/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [374]:
#sort time
dataNol = dataNoL.groupby(['userid']).apply(lambda x: x.sort_values(['time']))
#pd.concat([dataNol, piD], axis=1)
dataNol

                                       Unnamed: 0          hash  \
userid
009d96a823b6f6c085c092fb177491f6 4354        4407 -4.709960e+18
                                 4353        3752  7.933700e+18
                                 4370         829  2.667350e+18
                                 4347        2309  3.757630e+18
                                 4350        2937 -1.122940e+17
                                 4337         181 -5.528320e+18
                                 4343        1477  6.205630e+18
                                 4341        1172  4.652200e+18
                                 4346        2206 -5.155540e+18
                                 4344        2006 -4.992010e+18
                                 4342        1184  4.467830e+18
                                 4339         807 -7.507510e+18
                                 4348        2452 -6.242800e+18
                                 4351        3022 -6.912400e+18
                                 4345        2063 -8.992510e+18
                                 4340        1115  2.619700e+18
                                 4349        2659  4.100960e+18
                                 4338         272 -5.411250e+18
                                 4336         178  8.206340e+18
00c69df4ec41f61da30ed2874b9fbfaf 4334        4509 -8.668150e+18
011679a3ae49998801ada93d822b7302 4332        3041 -7.591030e+18
                                 4327        1913 -1.732750e+18
                                 4331        2477 -9.090120e+18
                                 4324         515  3.004290e+18
                                 4323         247 -1.998510e+18
                                 4328        2248  8.766730e+18
                                 4329        2249  4.032300e+18
                                 4333        4293 -9.192170e+18
                                 4325         639  5.491620e+18
                                 4330        2339 -2.036370e+18
...                                           ...           ...
fd054ad407abf163e6ec4334aacde10c 32          3154  8.787670e+17
fd5d700ef265d6f039a65db3d87f22df 29          1180  3.483810e+17
fdd59fbb907c5eb218de8b77cd0570c9 28          3253 -1.291080e+18
                                 4485        3635 -6.187470e+17
fdd7bb23407b15e190e70405063db57b 24          2431 -8.738620e+18
                                 26          3398 -8.818950e+18
                                 23           412 -7.413830e+18
                                 25          3387 -4.702130e+18
fdfdc49f0f563b1c4e1192b23cb990a1 21          1945 -8.080410e+18
                                 22          2967  2.578260e+18
                                 20          1227 -6.227790e+18
fe198dfc0551409e4767fdbe2abddbdf 4467        3275 -2.645730e+18
fe4e8d6bc63f4d75771c0f0d9e7e152b 18          2712  1.541440e+18
                                 19          3180  3.417980e+18
                                 4514        4177 -1.278050e+17
fe7c9c678bdb5dfb36e9ffa04ac0a1e7 16          4169 -6.815210e+18
ff7d6f0f87eb76e53dffbc4082367843 15           774  4.688260e+18
ff901930a5eaba2dc939d40571f51bb5 10          2473  2.728100e+18
                                 6           1751  6.846550e+18
                                 4           1341  6.019060e+16
                                 0            353  5.851210e+18
                                 3            890 -8.008550e+18
                                 8           1958 -3.730250e+18
                                 12          3561 -4.056720e+18
                                 14          4355  4.792250e+17
                                 13          4185  5.642180e+18
                                 11          2921 -7.165560e+18
                                 9           2419  7.331390e+18
                                 7           1878 -5.639940e+18
                                 5           1369 -1.271970e+18

                                                                                    text  \
userid
009d96a823b6f6c085c092fb177491f6 4354  Laughing because it's been 9 months and I'm st...
                                 4353  Dear FB friends.. I am writing to tell you tha...
                                 4370  There is nothing else to proof Now you still d...
                                 4347  So I have to verbally confirm with my brothers...
                                 4350  Every girl wants the guy they can fall for but...
                                 4337  Met up with Vitico and Yeslenny the day wad pr...
                                 4343  Is getting tired of people assuming she is a s...
                                 4341  I'm starting what I like to call project 365 I...
                                 4346  Why does everything open at 9am :( I really wi...
                                 4344  Life lives, life dies. Life laughs, life cries...
                                 4342  So apparently 3-5am was the designated time la...
                                 4339  For those of you still trying to text, and cal...
                                 4348  Running on low time to regain some power, awak...
                                 4351  Waiting for my Melissa Torres who had a rush t...
                                 4345  Is at a great party where all the good songs a...
                                 4340  Where am I, where am I going, I totally got CR...
                                 4349  High school student tells me I'm to beautiful ...
                                 4338  How do u expect kids 2 listen 2 their parents ...
                                 4336  What would your liqour do? If it could, it wou...
00c69df4ec41f61da30ed2874b9fbfaf 4334  Here lies John, who passed away  While answeri...
011679a3ae49998801ada93d822b7302 4332  loved how when I opened Interview with the Vam...
                                 4327  is really looking forward to the things that a...
                                 4331  I spend entirely too much time looking on Barn...
                                 4324  yay! broccoli soup for when I'm sick ftw! My m...
                                 4323  today, I shall clean the room! (I <3 My Greek ...
                                 4328  blames Ronda Freeland-Napier that I can't slee...
                                 4329  so I've finished stage 1 of my job hunt, the a...
                                 4333  Oh Busch why do you have to be so fun? You mak...
                                 4325  I swear to God I am going to shove q-tips in m...
                                 4330  good news, it's FINALLY Friday tomorrow.! Bad ...
...                                                                                  ...
fd054ad407abf163e6ec4334aacde10c 32    Aku ni asal negeri mana ar? lecturer phy193 ck...
fd5d700ef265d6f039a65db3d87f22df 29    just took my second shot of treat  ment. side ...
fdd59fbb907c5eb218de8b77cd0570c9 28    why is the online timetable system so rubbish!...
                                 4485  my phone is now completely dead, so need a new...
fdd7bb23407b15e190e70405063db57b 24    Why don't people live for their work? And why ...
                                 26    It is important to retain faith in one's inner...
                                 23    Hahah. Got to see those lovely, amazing, junio...
                                 25    /Apple is the WORST company ever!!/"  My favor...
fdfdc49f0f563b1c4e1192b23cb990a1 21    Just watched Waltz With Bashir. That whole Isr...
                                 22    I am inexplicably tired for some reason P.S. M...
                                 20    I got Revenge of the Sinister Six in the post ...
fe198dfc0551409e4767fdbe2abddbdf 4467  : â”¬Â½ And in the sea there is a fish, a fish...
fe4e8d6bc63f4d75771c0f0d9e7e152b 18    Thanks to all who wished me a happy birthday. ...
                                 19    I don't understand why people have such an ave...
                                 4514  It might be boring, so boring; it might put yo...
fe7c9c678bdb5dfb36e9ffa04ac0a1e7 16    Went on a simple trip to merr to get a pop, co...
ff7d6f0f87eb76e53dffbc4082367843 15    Thony Drew the cutest little picture of me XD,...
ff901930a5eaba2dc939d40571f51bb5 10    i get to go to my aunt's house for part of thi...
                                 6     *sighs* I just want to go home...sorta. There'...
                                 4     I'm fucking done. I don't need this type of sh...
                                 0     Is tired of life. I'm tired of always being bl...
                                 3     I'm home and happy to be back. already busy wi...
                                 8     I'm attempting to join the Marine Corps, all t...
                                 12    Don't even think of fucking pissing me off tod...
                                 14    you try to change me and I tell you that you'd...
                                 13    If you suddenly bump me out of your life, expe...
                                 11    Went to the doctor's today. she told me that I...
                                 9     I was just now told I looked like a vampyre by...
                                 7     Morning, everyone. Today's going to be blah wi...
                                 5     Dad's home for a month, he's going to be there...

                                                                score  \
userid
009d96a823b6f6c085c092fb177491f6 4354  [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
                                 4353  [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
                                 4370  [1, 1, 5, 1, 1, 1, 1, 1, 1, 1]
                                 4347  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 4350  [1, 1, 1, 1, 1, 3, 1, 1, 5, 0]
                                 4337  [5, 3, 1, 1, 0, 0, 0, 0, 0, 0]
                                 4343  [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
                                 4341  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 4346  [1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
                                 4344  [4, 4, 1, 1, 7, 3, 3, 1, 1, 0]
                                 4342  [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
                                 4339  [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
                                 4348  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 4351  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 4345  [1, 1, 1, 1, 1, 1, 1, 1, 3, 0]
                                 4340  [1, 1, 1, 3, 1, 1, 1, 1, 0, 0]
                                 4349  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 4338  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
                                 4336  [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
00c69df4ec41f61da30ed2874b9fbfaf 4334  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
011679a3ae49998801ada93d822b7302 4332  [1, 1, 3, 1, 1, 1, 3, 1, 1, 1]
                                 4327  [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
                                 4331  [1, 1, 1, 1, 1, 1, 1, 5, 1, 1]
                                 4324  [1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
                                 4323  [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
                                 4328  [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
                                 4329  [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
                                 4333  [3, 1, 1, 1, 5, 1, 0, 0, 0, 0]
                                 4325  [1, 1, 3, 1, 1, 1, 1, 1, 1, 0]
                                 4330  [1, 1, 5, 1, 1, 1, 1, 1, 1, 0]
...                                                               ...
fd054ad407abf163e6ec4334aacde10c 32    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
fd5d700ef265d6f039a65db3d87f22df 29    [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
fdd59fbb907c5eb218de8b77cd0570c9 28    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 4485  [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
fdd7bb23407b15e190e70405063db57b 24    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 26    [1, 1, 1, 1, 3, 1, 1, 3, 1, 1]
                                 23    [1, 1, 1, 1, 5, 1, 1, 1, 1, 0]
                                 25    [5, 5, 7, 3, 1, 5, 5, 1, 5, 0]
fdfdc49f0f563b1c4e1192b23cb990a1 21    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 22    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 20    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
fe198dfc0551409e4767fdbe2abddbdf 4467  [5, 3, 1, 1, 1, 1, 1, 1, 0, 0]
fe4e8d6bc63f4d75771c0f0d9e7e152b 18    [1, 1, 1, 1, 1, 1, 1, 5, 1, 0]
                                 19    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 4514  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
fe7c9c678bdb5dfb36e9ffa04ac0a1e7 16    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
ff7d6f0f87eb76e53dffbc4082367843 15    [3, 1, 1, 1, 1, 1, 1, 1, 1, 0]
ff901930a5eaba2dc939d40571f51bb5 10    [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
                                 6     [1, 1, 2, 1, 1, 1, 0, 0, 0, 0]
                                 4     [1, 3, 1, 1, 1, 1, 3, 1, 1, 1]
                                 0     [1, 1, 1, 1, 1, 1, 3, 1, 1, 1]
                                 3     [1, 1, 1, 1, 1, 3, 1, 3, 1, 0]
                                 8     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 12    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 14    [3, 3, 3, 5, 3, 1, 0, 0, 0, 0]
                                 13    [1, 5, 1, 1, 1, 1, 1, 1, 1, 1]
                                 11    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                                 9     [1, 1, 1, 1, 1, 1, 1, 1, 1, 5]
                                 7     [1, 1, 1, 3, 1, 1, 1, 1, 1, 0]
                                 5     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

                                                  cosineSim  result  \
userid
009d96a823b6f6c085c092fb177491f6 4354  [0.9137284834983139]       0
                                 4353   [0.918984845296597]       0
                                 4370  [0.9436753395742027]       0
                                 4347  [0.8574483354003295]       0
                                 4350  [0.7853461528124974]       0
                                 4337   [0.876034901275211]       0
                                 4343   [0.864139574909509]       0
                                 4341  [0.8387930445065489]       0
                                 4346  [0.8657502783061679]       0
                                 4344  [0.7340439330265127]       0
                                 4342  [0.7804755015801407]       0
                                 4339   [0.846874868182615]       0
                                 4348  [0.8738187766911816]       0
                                 4351  [0.9174029103929061]       0
                                 4345   [0.880874789793091]       0
                                 4340  [0.9221163644939693]       0
                                 4349  [0.9095813847357423]       0
                                 4338   [0.940875515563263]       0
                                 4336  [0.8347438500225349]       0
00c69df4ec41f61da30ed2874b9fbfaf 4334  [0.8799613978391074]       0
011679a3ae49998801ada93d822b7302 4332  [0.8779932000292979]       0
                                 4327  [0.7704183800060926]       0
                                 4331  [0.8309337617333065]       0
                                 4324  [0.9202043962922094]       0
                                 4323  [0.9055198553318163]       0
                                 4328  [0.8746116979151729]       0
                                 4329  [0.9252992359643607]       0
                                 4333  [0.7401928795834491]       0
                                 4325  [0.8586972147497802]       0
                                 4330  [0.9070431252574283]       0
...                                                     ...     ...
fd054ad407abf163e6ec4334aacde10c 32    [0.8672190487795179]       0
fd5d700ef265d6f039a65db3d87f22df 29    [0.8888094704425213]       0
fdd59fbb907c5eb218de8b77cd0570c9 28    [0.8703173244570285]       0
                                 4485  [0.8724076253795136]       0
fdd7bb23407b15e190e70405063db57b 24    [0.9338576606684698]       0
                                 26     [0.895351022213217]       0
                                 23    [0.9000373309682077]       0
                                 25    [0.8010289365605437]       0
fdfdc49f0f563b1c4e1192b23cb990a1 21    [0.8758953780244223]       0
                                 22     [0.860083535125094]       0
                                 20    [0.8633689732587316]       0
fe198dfc0551409e4767fdbe2abddbdf 4467  [0.8659439832972817]       0
fe4e8d6bc63f4d75771c0f0d9e7e152b 18     [0.881206963598104]       0
                                 19    [0.9112131109658743]       0
                                 4514  [0.9036087549753742]       0
fe7c9c678bdb5dfb36e9ffa04ac0a1e7 16    [0.9080647234651839]       0
ff7d6f0f87eb76e53dffbc4082367843 15    [0.9052816857199768]       0
ff901930a5eaba2dc939d40571f51bb5 10    [0.9248907511115738]       0
                                 6      [0.907178277633884]       0
                                 4     [0.9474686762925819]       0
                                 0     [0.8577051091000486]       0
                                 3     [0.8485114160205077]       0
                                 8     [0.8889395197373277]       0
                                 12    [0.8970060985257685]       0
                                 14    [0.8098411783922302]       0
                                 13    [0.9221753680613632]       0
                                 11     [0.903197100452946]       0
                                 9     [0.8640988576316313]       0
                                 7     [0.9090147957385997]       0
                                 5     [0.9437565621218282]       0

                                       negative_ny  distortion  magnitude  \
userid
009d96a823b6f6c085c092fb177491f6 4354          2.0         NaN        NaN
                                 4353          NaN         NaN        NaN
                                 4370          NaN         NaN        NaN
                                 4347          NaN         NaN        NaN
                                 4350          NaN         NaN        NaN
                                 4337          2.0         NaN        NaN
                                 4343          1.0         NaN        3.0
                                 4341          2.0         NaN        NaN
                                 4346          NaN         NaN        NaN
                                 4344          NaN         NaN        NaN
                                 4342          2.0         NaN        NaN
                                 4339          2.0         NaN        NaN
                                 4348          NaN         NaN        NaN
                                 4351          NaN         NaN        NaN
                                 4345          NaN         NaN        NaN
                                 4340          1.0         NaN        4.0
                                 4349          NaN         NaN        NaN
                                 4338          1.0         NaN        2.0
                                 4336          2.0         NaN        NaN
00c69df4ec41f61da30ed2874b9fbfaf 4334          1.0         NaN        3.0
011679a3ae49998801ada93d822b7302 4332          NaN         NaN        NaN
                                 4327          NaN         NaN        NaN
                                 4331          NaN         NaN        NaN
                                 4324          2.0         NaN        NaN

In [375]:
len(dataNol.index)

3881

3895

In [376]:
database_D[0:10]

,index,text,annotation,annotation_date,userid,ParticipantID,time
0,0,Dear FB friends.. I am writing to tell you tha...,0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2009-08-12 08:18:00
1,1,Laughing because it's been 9 months and I'm st...,0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2009-11-21 03:57:00
2,2,So I have to verbally confirm with my brothers...,0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-05-28 13:41:00
3,3,Every girl wants the guy they can fall for but...,0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-05-29 21:14:00
4,4,I'm starting what I like to call project 365 I...,0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-07-20 15:32:00
5,5,Why does everything open at 9am :( I really wi...,0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-07-21 11:35:00
6,6,"Life lives, life dies. Life laughs, life cries...",0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-07-27 22:54:00
7,7,Met up with Vitico and Yeslenny the day wad pr...,0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-08-07 06:11:00
8,8,"Running on low time to regain some power, awak...",0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-08-09 19:56:00
9,9,"For those of you still trying to text, and cal...",0,NaN,009d96a823b6f6c085c092fb177491f6,33442,2010-08-25 16:20:00

In [377]:
len(dataNoL.groupby(['userid']))

717

In [378]:
#combine userid and random participant id
userid  = pd.DataFrame(dataNoL['userid'])
userid = userid.drop_duplicates()
userid = userid.reset_index()

In [381]:
#now assign the three participant 
#generate an array with 3 numbers
pid = np.random.choice([44553, 22334, 33442], size=717)
piD = pd.DataFrame()
piD = piD.assign(ParticipantID = pid)
len(piD)
piD = piD.reset_index()
userid2 = pd.concat([userid,piD], axis= 1)

In [382]:
#merge them to the original df
data2 = pd.merge(dataNol, userid2, on = 'userid')
len(data2)

3881

In [383]:
data2

,Unnamed: 0,hash,text,score,cosineSim,result,negative_ny,distortion,magnitude,category,quote,userid,time,index,index,ParticipantID
0,4407,-4.709960e+18,Laughing because it's been 9 months and I'm st...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]",[0.9137284834983139],0,2.0,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2009-11-21 03:57:13,4336,707.0,33442.0
1,3752,7.933700e+18,Dear FB friends.. I am writing to tell you tha...,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]",[0.918984845296597],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2009-12-08 08:18:12,4336,707.0,33442.0
2,829,2.667350e+18,There is nothing else to proof Now you still d...,"[1, 1, 5, 1, 1, 1, 1, 1, 1, 1]",[0.9436753395742027],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-04-09 14:24:20,4336,707.0,33442.0
3,2309,3.757630e+18,So I have to verbally confirm with my brothers...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8574483354003295],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-05-28 13:41:48,4336,707.0,33442.0
4,2937,-1.122940e+17,Every girl wants the guy they can fall for but...,"[1, 1, 1, 1, 1, 3, 1, 1, 5, 0]",[0.7853461528124974],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-05-29 21:14:21,4336,707.0,33442.0
5,181,-5.528320e+18,Met up with Vitico and Yeslenny the day wad pr...,"[5, 3, 1, 1, 0, 0, 0, 0, 0, 0]",[0.876034901275211],0,2.0,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-07-08 06:11:28,4336,707.0,33442.0
6,1477,6.205630e+18,Is getting tired of people assuming she is a s...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]",[0.864139574909509],0,1.0,NaN,3.0,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-07-12 15:55:21,4336,707.0,33442.0
7,1172,4.652200e+18,I'm starting what I like to call project 365 I...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8387930445065489],0,2.0,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-07-20 15:32:31,4336,707.0,33442.0
8,2206,-5.155540e+18,Why does everything open at 9am :( I really wi...,"[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]",[0.8657502783061679],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-07-21 11:35:53,4336,707.0,33442.0
9,2006,-4.992010e+18,"Life lives, life dies. Life laughs, life cries...","[4, 4, 1, 1, 7, 3, 3, 1, 1, 0]",[0.7340439330265127],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-07-27 22:54:27,4336,707.0,33442.0
10,1184,4.467830e+18,So apparently 3-5am was the designated time la...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]",[0.7804755015801407],0,2.0,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-08-12 12:40:46,4336,707.0,33442.0
11,807,-7.507510e+18,"For those of you still trying to text, and cal...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]",[0.846874868182615],0,2.0,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-08-25 16:20:36,4336,707.0,33442.0
12,2452,-6.242800e+18,"Running on low time to regain some power, awak...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8738187766911816],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-09-08 19:56:09,4336,707.0,33442.0
13,3022,-6.912400e+18,Waiting for my Melissa Torres who had a rush t...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9174029103929061],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-09-19 18:59:29,4336,707.0,33442.0
14,2063,-8.992510e+18,Is at a great party where all the good songs a...,"[1, 1, 1, 1, 1, 1, 1, 1, 3, 0]",[0.880874789793091],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2010-12-22 02:10:00,4336,707.0,33442.0
15,1115,2.619700e+18,"Where am I, where am I going, I totally got CR...","[1, 1, 1, 3, 1, 1, 1, 1, 0, 0]",[0.9221163644939693],0,1.0,NaN,4.0,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2011-03-03 12:44:58,4336,707.0,33442.0
16,2659,4.100960e+18,High school student tells me I'm to beautiful ...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9095813847357423],0,NaN,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2011-03-31 12:49:04,4336,707.0,33442.0
17,272,-5.411250e+18,How do u expect kids 2 listen 2 their parents ...,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]",[0.940875515563263],0,1.0,NaN,2.0,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2011-04-20 20:36:38,4336,707.0,33442.0
18,178,8.206340e+18,"What would your liqour do? If it could, it wou...","[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]",[0.8347438500225349],0,2.0,NaN,NaN,NaN,NaN,009d96a823b6f6c085c092fb177491f6,2011-05-05 13:22:31,4336,707.0,33442.0
19,4509,-8.668150e+18,"Here lies John, who passed away While answeri...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8799613978391074],0,1.0,NaN,3.0,NaN,NaN,00c69df4ec41f61da30ed2874b9fbfaf,2011-02-23 16:52:10,4334,706.0,44553.0
20,3041,-7.591030e+18,loved how when I opened Interview with the Vam...,"[1, 1, 3, 1, 1, 1, 3, 1, 1, 1]",[0.8779932000292979],0,NaN,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2009-11-20 01:22:45,4323,705.0,22334.0
21,1913,-1.732750e+18,is really looking forward to the things that a...,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]",[0.7704183800060926],0,NaN,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2010-02-16 21:30:00,4323,705.0,22334.0
22,2477,-9.090120e+18,I spend entirely too much time looking on Barn...,"[1, 1, 1, 1, 1, 1, 1, 5, 1, 1]",[0.8309337617333065],0,NaN,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2010-03-10 01:32:50,4323,705.0,22334.0
23,515,3.004290e+18,yay! broccoli soup for when I'm sick ftw! My m...,"[1, 1, 1, 1, 1, 1, 1, 0, 0, 0]",[0.9202043962922094],0,2.0,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2010-04-19 19:19:14,4323,705.0,22334.0
24,247,-1.998510e+18,"today, I shall clean the room! (I <3 My Greek ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]",[0.9055198553318163],0,2.0,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2010-05-27 18:17:40,4323,705.0,22334.0
25,2248,8.766730e+18,blames Ronda Freeland-Napier that I can't slee...,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]",[0.8746116979151729],0,NaN,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2010-06-22 15:25:17,4323,705.0,22334.0
26,2249,4.032300e+18,"so I've finished stage 1 of my job hunt, the a...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]",[0.9252992359643607],0,NaN,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2010-08-23 18:43:11,4323,705.0,22334.0
27,4293,-9.192170e+18,Oh Busch why do you have to be so fun? You mak...,"[3, 1, 1, 1, 5, 1, 0, 0, 0, 0]",[0.7401928795834491],0,2.0,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2010-10-23 03:49:21,4323,705.0,22334.0
28,639,5.491620e+18,I swear to God I am going to shove q-tips in m...,"[1, 1, 3, 1, 1, 1, 1, 1, 1, 0]",[0.8586972147497802],0,1.0,NaN,4.0,NaN,NaN,011679a3ae49998801ada93d822b7302,2011-01-25 05:25:09,4323,705.0,22334.0
29,2339,-2.036370e+18,"good news, it's FINALLY Friday tomorrow.! Bad ...","[1, 1, 5, 1, 1, 1, 1, 1, 1, 0]",[0.9070431252574283],0,NaN,NaN,NaN,NaN,NaN,011679a3ae49998801ada93d822b7302,2011-03-10 23:24:03,4323,705.0,22334.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3851,3154,8.787670e+17,Aku ni asal negeri mana ar? lecturer phy193 ck...,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]",[0.8672190487795179],0,NaN,NaN,NaN,NaN,NaN,fd054ad407abf163e6ec4334aacde10c,2011-08-20 08:15:37,30,8.0,44553.0
3852,1180,3.483810e+17,just took my second shot of treat ment. side ...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]",[0.8888094704425213],0,2.0,NaN,NaN,NaN,NaN,fd5d700ef265d6f039a65db3d87f22df,2011-04-20 01:03:30,29,7.0,22334.0
3853,3253,-1.291080e+18,why is the online timetable system so rubbish!...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8703173244570285],0,NaN,NaN,NaN,NaN,NaN,fdd59fbb907c5eb218de8b77cd0570c9,2010-10-10 20:21:01,28,6.0,33442.0
3854,3635,-6.187470e+17,"my phone is now completely dead, so need a new...","[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]",[0.8724076253795136],0,NaN,NaN,NaN,NaN,NaN,fdd59fbb907c5eb218de8b77cd0570c9,2010-10-19 21:38:24,28,6.0,33442.0
3855,2431,-8.738620e+18,Why don't people live for their work? And why ...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9338576606684698],0,NaN,NaN,NaN,NaN,NaN,fdd7bb23407b15e190e70405063db57b,2010-09-15 00:20:09,23,5.0,44553.0
3856,3398,-8.818950e+18,It is important to retain faith in one's inner...,"[1, 1, 1, 1, 3, 1, 1, 3, 1, 1]",[0.895351022213217],0,NaN,NaN,NaN,NaN,NaN,fdd7bb23407b15e190e70405063db57b,2010-11-08 01:39:51,23,5.0,44553.0
3857,412,-7.413830e+18,"Hahah. Got to see those lovely, amazing, junio...","[1, 1, 1, 1, 5, 1, 1, 1, 1, 0]",[0.9000373309682077],0,2.0,NaN,NaN,NaN,NaN,fdd7bb23407b15e190e70405063db57b,2010-12-19 07:35:16,23,5.0,44553.0
3858,3387,-4.702130e+18,"/Apple is the WORST company ever!!/"" My favor...","[5, 5, 7, 3, 1, 5, 5, 1, 5, 0]",[0.8010289365605437],0,NaN,NaN,NaN,NaN,NaN,fdd7bb23407b15e190e70405063db57b,2011-03-23 06:36:00,23,5.0,44553.0
3859,1945,-8.080410e+18,Just watched Waltz With Bashir. That whole Isr...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8758953780244223],0,NaN,NaN,NaN,NaN,NaN,fdfdc49f0f563b1c4e1192b23cb990a1,2010-01-26 00:21:21,20,4.0,22334.0
3860,2967,2.578260e+18,I am inexplicably tired for some reason P.S. M...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.860083535125094],0,NaN,NaN,NaN,NaN,NaN,fdfdc49f0f563b1c4e1192b23cb990a1,2010-02-03 20:17:47,20,4.0,22334.0
3861,1227,-6.227790e+18,I got Revenge of the Sinister Six in the post ...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8633689732587316],0,2.0,NaN,NaN,NaN,NaN,fdfdc49f0f563b1c4e1192b23cb990a1,2010-10-17 23:52:58,20,4.0,22334.0
3862,3275,-2.645730e+18,": â”¬Â½ And in the sea there is a fish, a fish...","[5, 3, 1, 1, 1, 1, 1, 1, 0, 0]",[0.8659439832972817],0,NaN,NaN,NaN,NaN,NaN,fe198dfc0551409e4767fdbe2abddbdf,2010-08-05 15:08:20,4467,715.0,22334.0
3863,2712,1.541440e+18,Thanks to all who wished me a happy birthday. ...,"[1, 1, 1, 1, 1, 1, 1, 5, 1, 0]",[0.881206963598104],0,NaN,NaN,NaN,NaN,NaN,fe4e8d6bc63f4d75771c0f0d9e7e152b,2010-04-09 22:59:29,18,3.0,22334.0
3864,3180,3.417980e+18,I don't understand why people have such an ave...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9112131109658743],0,1.0,NaN,3.0,NaN,NaN,fe4e8d6bc63f4d75771c0f0d9e7e152b,2010-09-18 04:09:36,18,3.0,22334.0
3865,4177,-1.278050e+17,"It might be boring, so boring; it might put yo...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9036087549753742],0,NaN,NaN,NaN,NaN,NaN,fe4e8d6bc63f4d75771c0f0d9e7e152b,2011-01-21 07:51:34,18,3.0,22334.0
3866,4169,-6.815210e+18,"Went on a simple trip to merr to get a pop, co...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9080647234651839],0,1.0,NaN,4.0,NaN,NaN,fe7c9c678bdb5dfb36e9ffa04ac0a1e7,2009-12-02 05:07:23,16,2.0,44553.0
3867,774,4.688260e+18,"Thony Drew the cutest little picture of me XD,...","[3, 1, 1, 1, 1, 1, 1, 1, 1, 0]",[0.9052816857199768],0,2.0,NaN,NaN,NaN,NaN,ff7d6f0f87eb76e53dffbc4082367843,2010-11-03 01:24:28,15,1.0,22334.0
3868,2473,2.728100e+18,i get to go to my aunt's house for part of thi...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]",[0.9248907511115738],0,NaN,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2009-06-17 20:16:20,0,0.0,44553.0
3869,1751,6.846550e+18,*sighs* I just want to go home...sorta. There'...,"[1, 1, 2, 1, 1, 1, 0, 0, 0, 0]",[0.907178277633884],0,NaN,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2009-08-29 21:25:34,0,0.0,44553.0
3870,1341,6.019060e+16,I'm fucking done. I don't need this type of sh...,"[1, 3, 1, 1, 1, 1, 3, 1, 1, 1]",[0.9474686762925819],0,1.0,NaN,5.0,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2010-03-23 23:57:39,0,0.0,44553.0
3871,353,5.851210e+18,Is tired of life. I'm tired of always being bl...,"[1, 1, 1, 1, 1, 1, 3, 1, 1, 1]",[0.8577051091000486],0,1.0,NaN,3.0,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2010-05-18 20:55:03,0,0.0,44553.0
3872,890,-8.008550e+18,I'm home and happy to be back. already busy wi...,"[1, 1, 1, 1, 1, 3, 1, 3, 1, 0]",[0.8485114160205077],0,2.0,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2010-07-31 19:57:07,0,0.0,44553.0
3873,1958,-3.730250e+18,"I'm attempting to join the Marine Corps, all t...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8889395197373277],0,NaN,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2010-10-23 01:43:59,0,0.0,44553.0
3874,3561,-4.056720e+18,Don't even think of fucking pissing me off tod...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.8970060985257685],0,NaN,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2011-02-03 15:10:28,0,0.0,44553.0
3875,4355,4.792250e+17,you try to change me and I tell you that you'd...,"[3, 3, 3, 5, 3, 1, 0, 0, 0, 0]",[0.8098411783922302],0,1.0,NaN,2.0,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2011-02-10 15:58:59,0,0.0,44553.0
3876,4185,5.642180e+18,"If you suddenly bump me out of your life, expe...","[1, 5, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9221753680613632],0,1.0,NaN,3.0,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2011-03-02 16:14:07,0,0.0,44553.0
3877,2921,-7.165560e+18,Went to the doctor's today. she told me that I...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.903197100452946],0,NaN,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2011-03-04 04:48:37,0,0.0,44553.0
3878,2419,7.331390e+18,I was just now told I looked like a vampyre by...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 5]",[0.8640988576316313],0,NaN,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2011-03-04 17:59:38,0,0.0,44553.0
3879,1878,-5.639940e+18,"Morning, everyone. Today's going to be blah wi...","[1, 1, 1, 3, 1, 1, 1, 1, 1, 0]",[0.9090147957385997],0,NaN,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2011-03-16 14:56:43,0,0.0,44553.0
3880,1369,-1.271970e+18,"Dad's home for a month, he's going to be there...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",[0.9437565621218282],0,2.0,NaN,NaN,NaN,NaN,ff901930a5eaba2dc939d40571f51bb5,2011-03-31 04:19:44,0,0.0,44553.0

In [384]:
len(data2)

3881

This would be the cogntive distortion database

In [414]:
#dataNoL 
database_D = pd.DataFrame()
database_D = database_D.assign(id = database_D.index + 1)
database_D = database_D.assign (ParticipantID = data2['ParticipantID'])
database_D = database_D.assign (userid = data2['userid'])
database_D['text'] = data2['text']
database_D = database_D.assign (annotation = 0)
database_D = database_D.assign (annotation_date = np.nan)
database_D = database_D.assign (time = data2['time'])
database_D = database_D.reset_index()

database_D

,index,id,ParticipantID,userid,text,annotation,annotation_date,time
0,0,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Laughing because it's been 9 months and I'm st...,0,NaN,2009-11-21 03:57:13
1,1,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Dear FB friends.. I am writing to tell you tha...,0,NaN,2009-12-08 08:18:12
2,2,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,There is nothing else to proof Now you still d...,0,NaN,2010-04-09 14:24:20
3,3,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,So I have to verbally confirm with my brothers...,0,NaN,2010-05-28 13:41:48
4,4,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Every girl wants the guy they can fall for but...,0,NaN,2010-05-29 21:14:21
5,5,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Met up with Vitico and Yeslenny the day wad pr...,0,NaN,2010-07-08 06:11:28
6,6,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Is getting tired of people assuming she is a s...,0,NaN,2010-07-12 15:55:21
7,7,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,I'm starting what I like to call project 365 I...,0,NaN,2010-07-20 15:32:31
8,8,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Why does everything open at 9am :( I really wi...,0,NaN,2010-07-21 11:35:53
9,9,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,"Life lives, life dies. Life laughs, life cries...",0,NaN,2010-07-27 22:54:27
10,10,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,So apparently 3-5am was the designated time la...,0,NaN,2010-08-12 12:40:46
11,11,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,"For those of you still trying to text, and cal...",0,NaN,2010-08-25 16:20:36
12,12,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,"Running on low time to regain some power, awak...",0,NaN,2010-09-08 19:56:09
13,13,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Waiting for my Melissa Torres who had a rush t...,0,NaN,2010-09-19 18:59:29
14,14,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,Is at a great party where all the good songs a...,0,NaN,2010-12-22 02:10:00
15,15,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,"Where am I, where am I going, I totally got CR...",0,NaN,2011-03-03 12:44:58
16,16,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,High school student tells me I'm to beautiful ...,0,NaN,2011-03-31 12:49:04
17,17,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,How do u expect kids 2 listen 2 their parents ...,0,NaN,2011-04-20 20:36:38
18,18,NaN,33442.0,009d96a823b6f6c085c092fb177491f6,"What would your liqour do? If it could, it wou...",0,NaN,2011-05-05 13:22:31
19,19,NaN,44553.0,00c69df4ec41f61da30ed2874b9fbfaf,"Here lies John, who passed away While answeri...",0,NaN,2011-02-23 16:52:10
20,20,NaN,22334.0,011679a3ae49998801ada93d822b7302,loved how when I opened Interview with the Vam...,0,NaN,2009-11-20 01:22:45
21,21,NaN,22334.0,011679a3ae49998801ada93d822b7302,is really looking forward to the things that a...,0,NaN,2010-02-16 21:30:00
22,22,NaN,22334.0,011679a3ae49998801ada93d822b7302,I spend entirely too much time looking on Barn...,0,NaN,2010-03-10 01:32:50
23,23,NaN,22334.0,011679a3ae49998801ada93d822b7302,yay! broccoli soup for when I'm sick ftw! My m...,0,NaN,2010-04-19 19:19:14
24,24,NaN,22334.0,011679a3ae49998801ada93d822b7302,"today, I shall clean the room! (I <3 My Greek ...",0,NaN,2010-05-27 18:17:40
25,25,NaN,22334.0,011679a3ae49998801ada93d822b7302,blames Ronda Freeland-Napier that I can't slee...,0,NaN,2010-06-22 15:25:17
26,26,NaN,22334.0,011679a3ae49998801ada93d822b7302,"so I've finished stage 1 of my job hunt, the a...",0,NaN,2010-08-23 18:43:11
27,27,NaN,22334.0,011679a3ae49998801ada93d822b7302,Oh Busch why do you have to be so fun? You mak...,0,NaN,2010-10-23 03:49:21
28,28,NaN,22334.0,011679a3ae49998801ada93d822b7302,I swear to God I am going to shove q-tips in m...,0,NaN,2011-01-25 05:25:09
29,29,NaN,22334.0,011679a3ae49998801ada93d822b7302,"good news, it's FINALLY Friday tomorrow.! Bad ...",0,NaN,2011-03-10 23:24:03
...,...,...,...,...,...,...,...,...
3851,3851,NaN,44553.0,fd054ad407abf163e6ec4334aacde10c,Aku ni asal negeri mana ar? lecturer phy193 ck...,0,NaN,2011-08-20 08:15:37
3852,3852,NaN,22334.0,fd5d700ef265d6f039a65db3d87f22df,just took my second shot of treat ment. side ...,0,NaN,2011-04-20 01:03:30
3853,3853,NaN,33442.0,fdd59fbb907c5eb218de8b77cd0570c9,why is the online timetable system so rubbish!...,0,NaN,2010-10-10 20:21:01
3854,3854,NaN,33442.0,fdd59fbb907c5eb218de8b77cd0570c9,"my phone is now completely dead, so need a new...",0,NaN,2010-10-19 21:38:24
3855,3855,NaN,44553.0,fdd7bb23407b15e190e70405063db57b,Why don't people live for their work? And why ...,0,NaN,2010-09-15 00:20:09
3856,3856,NaN,44553.0,fdd7bb23407b15e190e70405063db57b,It is important to retain faith in one's inner...,0,NaN,2010-11-08 01:39:51
3857,3857,NaN,44553.0,fdd7bb23407b15e190e70405063db57b,"Hahah. Got to see those lovely, amazing, junio...",0,NaN,2010-12-19 07:35:16
3858,3858,NaN,44553.0,fdd7bb23407b15e190e70405063db57b,"/Apple is the WORST company ever!!/"" My favor...",0,NaN,2011-03-23 06:36:00
3859,3859,NaN,22334.0,fdfdc49f0f563b1c4e1192b23cb990a1,Just watched Waltz With Bashir. That whole Isr...,0,NaN,2010-01-26 00:21:21
3860,3860,NaN,22334.0,fdfdc49f0f563b1c4e1192b23cb990a1,I am inexplicably tired for some reason P.S. M...,0,NaN,2010-02-03 20:17:47
3861,3861,NaN,22334.0,fdfdc49f0f563b1c4e1192b23cb990a1,I got Revenge of the Sinister Six in the post ...,0,NaN,2010-10-17 23:52:58
3862,3862,NaN,22334.0,fe198dfc0551409e4767fdbe2abddbdf,": â”¬Â½ And in the sea there is a fish, a fish...",0,NaN,2010-08-05 15:08:20
3863,3863,NaN,22334.0,fe4e8d6bc63f4d75771c0f0d9e7e152b,Thanks to all who wished me a happy birthday. ...,0,NaN,2010-04-09 22:59:29
3864,3864,NaN,22334.0,fe4e8d6bc63f4d75771c0f0d9e7e152b,I don't understand why people have such an ave...,0,NaN,2010-09-18 04:09:36
3865,3865,NaN,22334.0,fe4e8d6bc63f4d75771c0f0d9e7e152b,"It might be boring, so boring; it might put yo...",0,NaN,2011-01-21 07:51:34
3866,3866,NaN,44553.0,fe7c9c678bdb5dfb36e9ffa04ac0a1e7,"Went on a simple trip to merr to get a pop, co...",0,NaN,2009-12-02 05:07:23
3867,3867,NaN,22334.0,ff7d6f0f87eb76e53dffbc4082367843,"Thony Drew the cutest little picture of me XD,...",0,NaN,2010-11-03 01:24:28
3868,3868,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,i get to go to my aunt's house for part of thi...,0,NaN,2009-06-17 20:16:20
3869,3869,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,*sighs* I just want to go home...sorta. There'...,0,NaN,2009-08-29 21:25:34
3870,3870,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,I'm fucking done. I don't need this type of sh...,0,NaN,2010-03-23 23:57:39
3871,3871,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,Is tired of life. I'm tired of always being bl...,0,NaN,2010-05-18 20:55:03
3872,3872,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,I'm home and happy to be back. already busy wi...,0,NaN,2010-07-31 19:57:07
3873,3873,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,"I'm attempting to join the Marine Corps, all t...",0,NaN,2010-10-23 01:43:59
3874,3874,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,Don't even think of fucking pissing me off tod...,0,NaN,2011-02-03 15:10:28
3875,3875,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,you try to change me and I tell you that you'd...,0,NaN,2011-02-10 15:58:59
3876,3876,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,"If you suddenly bump me out of your life, expe...",0,NaN,2011-03-02 16:14:07
3877,3877,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,Went to the doctor's today. she told me that I...,0,NaN,2011-03-04 04:48:37
3878,3878,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,I was just now told I looked like a vampyre by...,0,NaN,2011-03-04 17:59:38
3879,3879,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,"Morning, everyone. Today's going to be blah wi...",0,NaN,2011-03-16 14:56:43
3880,3880,NaN,44553.0,ff901930a5eaba2dc939d40571f51bb5,"Dad's home for a month, he's going to be there...",0,NaN,2011-03-31 04:19:44

#need to merge time with post so that users also see the time

In [415]:
database_D['time'] = database_D['time'].apply(lambda x: x.strftime('(%m/%d/%Y %H:%M:%S)'))

In [416]:
database_D['new_text'] = database_D[['text', 'time']].apply(lambda x: ''.join(x), axis=1)

In [417]:
database_D['new_text'][1:10]

1    Dear FB friends.. I am writing to tell you tha...
2    There is nothing else to proof Now you still d...
3    So I have to verbally confirm with my brothers...
4    Every girl wants the guy they can fall for but...
5    Met up with Vitico and Yeslenny the day wad pr...
6    Is getting tired of people assuming she is a s...
7    I'm starting what I like to call project 365 I...
8    Why does everything open at 9am :( I really wi...
9    Life lives, life dies. Life laughs, life cries...
Name: new_text, dtype: object

In [418]:
database_D.to_csv('Distortion_DB.csv')